name: Action to build and publish the project package into a GH package registry

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./AutorizacionMiddleware/Autorizacion.Middleware

      - name: Build
        run: dotnet build --no-restore
        working-directory: ./AutorizacionMiddleware/Autorizacion.Middleware

      - name: Pack
        run: dotnet pack -c Release
        working-directory: ./AutorizacionMiddleware/Autorizacion.Middleware

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: autorizacion
          path: ./AutorizacionMiddleware/Autorizacion.Middleware/bin/Release/*.nupkg
          if-no-files-found: error
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: autorizacion

      - name: List files
        run: ls -R

      - name: Prep packages
        run: dotnet nuget add source --username diegoalonsonm --password ${{ secrets.SECRET_PAQUETES }} --store-password-in-clear-text --name paquetes "https://nuget.pkg.github.com/diegoalonsonm/index.json"

      - name: Push package
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.SECRET_PAQUETES }} --source paquetes

# comando para agregar el source
# dotnet nuget add source "https://nuget.pkg.github.com/diegoalonsonm/index.json" --name "Paquetes" --username "diegoalonsonm" --password PAT --store-password-in-clear-text
